# Generated by Django 2.1.1 on 2018-09-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('arxiv', models.URLField(blank=True, max_length=1000, null=True)),
                ('slides', models.URLField(blank=True, max_length=1000, null=True)),
                ('talk', models.URLField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='files/papers')),
                ('reviews', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
