# Generated by Django 2.1.1 on 2018-09-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180907_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
