# Generated by Django 2.1.1 on 2018-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='subslug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='visible',
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default='courses/computer-vision', max_length=100),
            preserve_default=False,
        ),
    ]
